apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-mlops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-mlops-api
  template:
    metadata:
      labels:
        app: iris-mlops-api
    spec:
      containers:
        - name: iris-mlops-api
          image: stelabiju/iris-mlops-api:9f3a8de6b9f74d60fb8b1ff182554b21ce725216
          ports:
            - containerPort: 8000