apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-mlops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-mlops-api
  template:
    metadata:
      labels:
        app: iris-mlops-api
    spec:
      containers:
        - name: iris-mlops-api
          image: stelabiju/iris-mlops-api:4e25b8a99f37edf08984cc219e6a0bcd73fa68f7
          ports:
            - containerPort: 8000