apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-mlops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-mlops-api
  template:
    metadata:
      labels:
        app: iris-mlops-api
    spec:
      containers:
        - name: iris-mlops-api
          image: stelabiju/iris-mlops-api:9d39515872f6a7563175d37638552f018ec4771b
          ports:
            - containerPort: 8000